# Generated by Django 4.0.2 on 2022-02-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_created_at_doctor_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='entez le nom', max_length=100, verbose_name='name')),
                ('email', models.EmailField(help_text="entez l'email", max_length=100, verbose_name='email')),
                ('subject', models.CharField(help_text='entez le subject', max_length=100, null=True, verbose_name='subject')),
                ('message', models.TextField(help_text='entez le message', max_length=500, null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
